version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "latest"
  jobs:
    install:
      - npm ci
    build:
      html:
        - npm run docs:build
        - mkdir -p $READTHEDOCS_OUTPUT
        - mv .vitepress/dist $READTHEDOCS_OUTPUT/html
