version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "latest"
  jobs:
    install:
      - npm install vitepress
    build:
      html:
        - vitepress build
        - mkdir -p $READTHEDOCS_OUTPUT
        - mv .vitepress/dist $READTHEDOCS_OUTPUT/html
